### ISSUE TITLE
Doesnt seem to work with calibre 6

### ISSUE THREAD

**Issue by aCID-sLAM** [komali2/calibre-find-duplicates#1]
I tried using the plugin with Calibre 6.1.3 but the plugin wont show in the GUI.

Going back to to Calibre 5.44 lets the Plugin working again. Is there a way, that can be fixed?
This plugin fork is the only way to handle huge book librarys with dupes.

**Comment by komali2** [comment]
Ok, thank  you for pointing this out, I was just having the same issue actually lol. Lemme take a look!

**Comment by komali2** [comment]
Updated on main branch, does that work on your end as well?

**Comment by aCID-sLAM** [comment]
Yes. Works fine for me now too. Thanks!
